version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: mono-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mono-app
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  db:
    driver: local